### ISSUE TITLE
Ensure all hands-on instructions use "main" instead of "master"

### ISSUE THREAD

**Issue by bernhold** [bssw-tutorial/bssw-tutorial.github.io#24]
We need to check for any instructions that refer to master branch and change it to main. The h-n-w repo already uses main, and we've just changed the git-workflows presentation over to use main.  I think the hands-on exercises are the last place.

**Comment by pagrubel** [comment]
@bernhold  Is the following where you want us to work on the hands on material. I did check it there is no reference to master.

https://github.com/bssw-tutorial/bssw-tutorial.github.io/tree/main/2021-11-15-sc

**Comment by bernhold** [comment]
Yes, that's the correct place for the upcoming tutorial (we're not going to change the past versions).  I've you've checked, then I guess we can close this.  Thanks!
